package com.training.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Data implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("申請データチェック結果")
	private java.lang.Boolean dataCheckFlg;
	@org.kie.api.definition.type.Label("承認結果")
	private java.lang.Boolean approvalFlg;
	@org.kie.api.definition.type.Label("自動承認フラグ")
	private java.lang.Boolean autoApprovalFlg;

	public Data() {
	}

	public java.lang.Boolean getDataCheckFlg() {
		return this.dataCheckFlg;
	}

	public void setDataCheckFlg(java.lang.Boolean dataCheckFlg) {
		this.dataCheckFlg = dataCheckFlg;
	}

	public java.lang.Boolean getApprovalFlg() {
		return this.approvalFlg;
	}

	public void setApprovalFlg(java.lang.Boolean approvalFlg) {
		this.approvalFlg = approvalFlg;
	}

	public java.lang.Boolean getAutoApprovalFlg() {
		return this.autoApprovalFlg;
	}

	public void setAutoApprovalFlg(java.lang.Boolean autoApprovalFlg) {
		this.autoApprovalFlg = autoApprovalFlg;
	}

	public Data(java.lang.Boolean dataCheckFlg, java.lang.Boolean approvalFlg,
			java.lang.Boolean autoApprovalFlg) {
		this.dataCheckFlg = dataCheckFlg;
		this.approvalFlg = approvalFlg;
		this.autoApprovalFlg = autoApprovalFlg;public class Data {
            
        }
    }
}